name: stats_course
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - astropy
  - pandas
  - emcee
  - jax
  - flax
  - jaxopt
  - optax
  - tqdm
  - tinygp
  - arviz
  - corner
  - dynesty
  - pip
  - pip:
    - tensorflow-probability[jax]